Update link for script2(create bucket)

diff --git a/create-bucket b/create-bucket
--- a/create-bucket
+++ b/create-bucket
@@ -8,30 +8,19 @@ fi
 
 # pass the bucket name as a positional parameter
 bucket_name=$1
-REGION="us-west-2"
+region="us-west-2"
 
 # Check if the bucket exists
 if aws s3api head-bucket --bucket "$bucket_name" 2>/dev/null; then
     echo "Bucket $bucket_name already exists."
 else
   # create the bucket
-  echo $bucket_name
-fi
-
-
-#!/bin/bash
-
-# Create an S3 bucket
-BUCKET_NAME="unique-bucket-name-$RANDOM"
-REGION="us-west-2"
-
-aws s3api create-bucket \
-  --bucket "$BUCKET_NAME" \
-  --region "$REGION" \
-  --create-bucket-configuration LocationConstraint="$REGION"
-
-if [ $? -eq 0 ]; then
-  echo "Bucket '$BUCKET_NAME' created successfully in region '$REGION'."
-else
-  echo "Failed to create bucket."
+  if aws s3api create-bucket \
+        --bucket "$bucket_name" \
+        --region "$region" \
+        --create-bucket-configuration LocationConstraint="$region"; then
+        echo "Bucket $bucket_name created successfully in region $region."
+    else
+        echo "Failed to create bucket $bucket_name."
+        exit 1
 fi
